[package]
name = "ultra"
version = "0.1.0"
authors = ["Kevin Yap <me@kevinyap.ca>"]
description = "Cryptanalysis of the Engima in Rust."
keywords = ["enigma", "cryptanalysis"]
homepage = "https://github.com/iKevinY/ultra.rs"
repository = "https://github.com/iKevinY/ultra.rs"
readme = "README.md"
license = "MIT"

[[bin]]
name = "ultra"
path = "src/main.rs"
test = false
doc = false

[lib]
path = "src/lib.rs"
