[package]
name = "ultra"
version = "0.1.0"
authors = ["Kevin Yap <me@kevinyap.ca>"]
description = "Cryptanalysis of the Engima."
keywords = ["enigma", "cryptanalysis"]
homepage = "https://github.com/iKevinY/ultra"
repository = "https://github.com/iKevinY/ultra"
documentation = "https://docs.rs/ultra"
readme = "README.md"
license = "MIT"

[[bin]]
name = "ultra"
path = "src/main.rs"
test = false
doc = false

[lib]
path = "src/lib.rs"

[dependencies]
clap = "2.18.0"
itertools = "0.5.4"
lazy_static = "0.2.2"
